service: stackoverflow-fanatic

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-2

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  login:
    handler: handler.login
    environment:
      STACKOVERFLOW_EMAIL: shanehopcroft@hotmail.com
      STACKOVERFLOW_PASSWORD: <REDACTED>
      STACKOVERFLOW_DISPLAYNAME: Hoppy