service: stackoverflow-fanatic

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2

functions:
  login:
    handler: handler.login
    memorySize: 2048
    timeout: 30
    events:
      - schedule: rate(3 hours)
    environment:
      STACKOVERFLOW_EMAIL: ${ssm:/StackOverflowFanatic/StackOverflow/Email}
      STACKOVERFLOW_PASSWORD: ${ssm:/StackOverflowFanatic/StackOverflow/Password}
      STACKOVERFLOW_DISPLAYNAME: ${ssm:/StackOverflowFanatic/StackOverflow/DisplayName}